"""Internal Matching Engine for paper-mode order simulation.

Provides a lightweight CLOB (Central Limit Order Book) that agents can
submit orders to in paper mode, receiving realistic fills without
touching external venues.

Wired into the loop via ``get_matching_engine()`` singleton.
Config-driven from ``merid.paper_config.MatchingEngineConfig``.

Usage:
  engine = get_matching_engine("prediction")
  fill = engine.submit_order(order)
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

from utils.logger import get_logger

logger = get_logger(__name__)


# ── Enums ────────────────────────────────────────────────────────────

class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderStatus(str, Enum):
    PENDING = "pending"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class FillType(str, Enum):
    MAKER = "maker"
    TAKER = "taker"
    SELF = "self"       # Internal paper fill (no counterparty)


# ── Data objects ─────────────────────────────────────────────────────

@dataclass
class Order:
    """An order submitted to the matching engine."""
    order_id: str = ""
    instrument_id: str = ""
    side: OrderSide = OrderSide.BUY
    price: float = 0.0          # Limit price (0 = market)
    quantity: float = 0.0
    notional_usd: float = 0.0
    domain: str = ""
    agent_id: str = ""
    plan_id: str = ""
    status: OrderStatus = OrderStatus.PENDING
    submitted_at: float = 0.0
    filled_at: float = 0.0
    filled_quantity: float = 0.0
    filled_price: float = 0.0

    def __post_init__(self):
        if not self.order_id:
            self.order_id = f"ME-{uuid.uuid4().hex[:12]}"
        if not self.submitted_at:
            self.submitted_at = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "order_id": self.order_id,
            "instrument_id": self.instrument_id,
            "side": self.side.value,
            "price": self.price,
            "quantity": self.quantity,
            "notional_usd": self.notional_usd,
            "domain": self.domain,
            "agent_id": self.agent_id,
            "plan_id": self.plan_id,
            "status": self.status.value,
            "submitted_at": self.submitted_at,
            "filled_at": self.filled_at,
            "filled_quantity": self.filled_quantity,
            "filled_price": self.filled_price,
        }


@dataclass
class Fill:
    """A fill generated by the matching engine."""
    fill_id: str = ""
    order_id: str = ""
    instrument_id: str = ""
    side: OrderSide = OrderSide.BUY
    price: float = 0.0
    quantity: float = 0.0
    notional_usd: float = 0.0
    fill_type: FillType = FillType.SELF
    timestamp: float = 0.0

    def __post_init__(self):
        if not self.fill_id:
            self.fill_id = f"MF-{uuid.uuid4().hex[:12]}"
        if not self.timestamp:
            self.timestamp = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "fill_id": self.fill_id,
            "order_id": self.order_id,
            "instrument_id": self.instrument_id,
            "side": self.side.value,
            "price": self.price,
            "quantity": self.quantity,
            "notional_usd": self.notional_usd,
            "fill_type": self.fill_type.value,
            "timestamp": self.timestamp,
        }


@dataclass
class BookLevel:
    """A single price level in the order book."""
    price: float = 0.0
    quantity: float = 0.0
    order_count: int = 0


@dataclass
class BookSnapshot:
    """Current state of the order book for an instrument."""
    instrument_id: str = ""
    bids: List[BookLevel] = field(default_factory=list)
    asks: List[BookLevel] = field(default_factory=list)
    last_trade_price: float = 0.0
    last_trade_time: float = 0.0
    spread: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "instrument_id": self.instrument_id,
            "bids": [{"price": b.price, "quantity": b.quantity, "orders": b.order_count} for b in self.bids],
            "asks": [{"price": a.price, "quantity": a.quantity, "orders": a.order_count} for a in self.asks],
            "last_trade_price": self.last_trade_price,
            "last_trade_time": self.last_trade_time,
            "spread": self.spread,
        }


# ── Matching Engine ──────────────────────────────────────────────────

class MatchingEngine:
    """Lightweight CLOB matching engine for paper-mode order simulation.

    In paper mode, orders are filled immediately at the reference price
    (mid-market or last trade) with configurable slippage. This gives
    agents a realistic execution experience without external venue calls.

    For prediction markets, the reference price is the implied probability
    (0-100 cents), so a BUY at 65 means "buy YES at 65 cents".
    """

    def __init__(
        self,
        domain: str,
        engine_type: str = "clob",
        max_book_depth: int = 50,
        tick_size: float = 0.01,
        slippage_bps: float = 5.0,     # 5 bps default slippage
    ):
        self.domain = domain
        self.engine_type = engine_type
        self.max_book_depth = max_book_depth
        self.tick_size = tick_size
        self.slippage_bps = slippage_bps

        # State
        self._orders: Dict[str, Order] = {}
        self._fills: List[Fill] = []
        self._reference_prices: Dict[str, float] = {}  # instrument -> mid price
        self._enabled = False

        logger.info(
            f"MatchingEngine initialized: domain={domain}, type={engine_type}, "
            f"depth={max_book_depth}, tick={tick_size}"
        )

    @classmethod
    def from_config(cls, domain: str) -> "MatchingEngine":
        """Create a MatchingEngine from the paper_config for a domain."""
        from merid.paper_config import DOMAIN_CONFIGS
        dc = DOMAIN_CONFIGS.get(domain)
        if not dc or not dc.matching_engine:
            return cls(domain=domain, engine_type="clob")

        mc = dc.matching_engine
        engine = cls(
            domain=domain,
            engine_type=mc.engine_type,
            max_book_depth=mc.max_book_depth,
            tick_size=mc.tick_size,
        )
        engine._enabled = mc.enabled
        return engine

    @property
    def enabled(self) -> bool:
        return self._enabled

    def enable(self):
        self._enabled = True
        logger.info(f"MatchingEngine[{self.domain}] ENABLED")

    def disable(self):
        self._enabled = False
        logger.info(f"MatchingEngine[{self.domain}] DISABLED")

    # ── Reference price management ─────────────────────────────────

    def update_reference_price(self, instrument_id: str, price: float):
        """Update the reference (mid-market) price for an instrument."""
        self._reference_prices[instrument_id] = price

    def get_reference_price(self, instrument_id: str) -> Optional[float]:
        return self._reference_prices.get(instrument_id)

    def update_reference_prices(self, prices: Dict[str, float]):
        """Bulk update reference prices."""
        self._reference_prices.update(prices)

    # ── Order submission ───────────────────────────────────────────

    def submit_order(self, order: Order) -> Fill:
        """Submit an order and get an immediate paper fill.

        In paper mode, all orders fill at the reference price ± slippage.
        Returns a Fill object. Rejects if no reference price is available.
        """
        if not self._enabled:
            order.status = OrderStatus.REJECTED
            self._orders[order.order_id] = order
            logger.warning(f"MatchingEngine[{self.domain}] rejected {order.order_id}: engine disabled")
            return Fill(
                order_id=order.order_id,
                instrument_id=order.instrument_id,
                side=order.side,
                price=0.0,
                quantity=0.0,
                fill_type=FillType.SELF,
            )

        ref_price = self._reference_prices.get(order.instrument_id)
        if ref_price is None or ref_price <= 0:
            order.status = OrderStatus.REJECTED
            self._orders[order.order_id] = order
            logger.warning(
                f"MatchingEngine[{self.domain}] rejected {order.order_id}: "
                f"no reference price for {order.instrument_id}"
            )
            return Fill(
                order_id=order.order_id,
                instrument_id=order.instrument_id,
                side=order.side,
                price=0.0,
                quantity=0.0,
                fill_type=FillType.SELF,
            )

        # Apply slippage
        slip = ref_price * (self.slippage_bps / 10000.0)
        if order.side == OrderSide.BUY:
            fill_price = ref_price + slip
        else:
            fill_price = ref_price - slip

        # Round to tick size
        if self.tick_size > 0:
            fill_price = round(fill_price / self.tick_size) * self.tick_size

        # Determine fill quantity
        fill_qty = order.quantity
        if fill_qty <= 0 and order.notional_usd > 0 and fill_price > 0:
            fill_qty = order.notional_usd / fill_price

        fill_notional = fill_qty * fill_price

        # Create fill
        now = time.time()
        fill = Fill(
            order_id=order.order_id,
            instrument_id=order.instrument_id,
            side=order.side,
            price=round(fill_price, 8),
            quantity=round(fill_qty, 8),
            notional_usd=round(fill_notional, 2),
            fill_type=FillType.SELF,
            timestamp=now,
        )

        # Update order
        order.status = OrderStatus.FILLED
        order.filled_at = now
        order.filled_quantity = fill.quantity
        order.filled_price = fill.price
        self._orders[order.order_id] = order
        self._fills.append(fill)

        # Update reference price (last trade)
        self._reference_prices[order.instrument_id] = fill.price

        logger.info(
            f"MatchingEngine[{self.domain}] FILL {order.order_id}: "
            f"{order.side.value} {fill.quantity:.4f} {order.instrument_id} "
            f"@ {fill.price:.4f} (${fill.notional_usd:.2f})"
        )

        return fill

    # ── Book snapshot (synthetic) ──────────────────────────────────

    def get_book(self, instrument_id: str) -> BookSnapshot:
        """Generate a synthetic order book around the reference price."""
        ref = self._reference_prices.get(instrument_id, 0.0)
        if ref <= 0:
            return BookSnapshot(instrument_id=instrument_id)

        bids = []
        asks = []
        for i in range(min(self.max_book_depth, 10)):
            offset = (i + 1) * self.tick_size
            bids.append(BookLevel(
                price=round(ref - offset, 8),
                quantity=round(10.0 * (1 + i * 0.5), 2),
                order_count=1 + i,
            ))
            asks.append(BookLevel(
                price=round(ref + offset, 8),
                quantity=round(10.0 * (1 + i * 0.5), 2),
                order_count=1 + i,
            ))

        spread = 2 * self.tick_size
        return BookSnapshot(
            instrument_id=instrument_id,
            bids=bids,
            asks=asks,
            last_trade_price=ref,
            last_trade_time=time.time(),
            spread=round(spread, 8),
        )

    # ── Query ──────────────────────────────────────────────────────

    def get_order(self, order_id: str) -> Optional[Order]:
        return self._orders.get(order_id)

    def recent_fills(self, limit: int = 50) -> List[Fill]:
        return self._fills[-limit:]

    def fills_for_instrument(self, instrument_id: str, limit: int = 50) -> List[Fill]:
        return [f for f in self._fills if f.instrument_id == instrument_id][-limit:]

    def open_orders(self) -> List[Order]:
        return [o for o in self._orders.values() if o.status == OrderStatus.PENDING]

    def stats(self) -> Dict[str, Any]:
        return {
            "domain": self.domain,
            "enabled": self._enabled,
            "engine_type": self.engine_type,
            "total_orders": len(self._orders),
            "total_fills": len(self._fills),
            "instruments_tracked": len(self._reference_prices),
            "reference_prices": dict(self._reference_prices),
        }

    def reset(self):
        """Clear all orders, fills, and reference prices."""
        self._orders.clear()
        self._fills.clear()
        self._reference_prices.clear()
        logger.info(f"MatchingEngine[{self.domain}] RESET")


# ── Singleton registry ───────────────────────────────────────────────

_engines: Dict[str, MatchingEngine] = {}


def get_matching_engine(domain: str) -> MatchingEngine:
    """Get or create the matching engine for a domain."""
    if domain not in _engines:
        _engines[domain] = MatchingEngine.from_config(domain)
    return _engines[domain]


def init_matching_engines() -> Dict[str, MatchingEngine]:
    """Initialize matching engines for all domains that have them configured.

    Called at loop startup. Returns dict of domain -> engine.
    Also registers venue adapters for domains with venues.
    """

    from merid.paper_config import DOMAIN_CONFIGS

    engines = {}
    for name, dc in DOMAIN_CONFIGS.items():
        if dc.matching_engine and dc.matching_engine.enabled and dc.enabled:
            engine = get_matching_engine(name)
            engines[name] = engine
            logger.info(
                f"Matching engine ready: domain={name}, "
                f"type={engine.engine_type}, enabled={engine.enabled}"
            )
            
            # Initialize venue registry for domains with venues
            if dc.venues and "kalshi" in dc.venues:
                try:
                    from merid.venue_registry import get_venue_registry
                    registry = get_venue_registry()
                    logger.info(f"Venue registry initialized for {name} domain")
                except Exception as exc:
                    logger.warning(f"Failed to initialize venue registry for {name}: {exc}")
    
    return engines


def all_engine_stats() -> Dict[str, Dict[str, Any]]:
    """Return stats for all initialized engines."""
    return {domain: engine.stats() for domain, engine in _engines.items()}
