version: '3.9'
services:
  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    ports:
      - "5000:5000"
    environment:
      - WHOOGLE_CONFIG_DARK=1
      - WHOOGLE_CONFIG_THEME=system
      - WHOOGLE_CONFIG_SAFE=1
    restart: unless-stopped
