#!/usr/bin/env python3
"""
Kalshi Credential Setup Helper

This script helps set up Kalshi API credentials for MERID.

Steps:
1. Log into your Kalshi account at https://kalshi.com
2. Go to Settings → API Keys
3. Create a new API key pair
4. Download the private key file
5. Run this script to create your .env file
"""

import os
import sys
from pathlib import Path

def main():
    print("=" * 60)
    print("Kalshi Credential Setup for MERID")
    print("=" * 60)
    print()
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print("\nPlease enter your Kalshi API credentials:")
    print("(Get these from https://kalshi.com → Settings → API Keys)")
    print()
    
    # Get credentials from user
    key_id = input("KALSHI_API_KEY_ID: ").strip()
    
    private_key_path = input("Path to kalshi_private_key.pem: ").strip()
    # Expand user path (e.g., ~ → /home/user)
    private_key_path = os.path.expanduser(private_key_path)
    
    # Validate key file exists
    if not os.path.exists(private_key_path):
        print(f"\n⚠️  Warning: Private key file not found at {private_key_path}")
        print("Make sure to download the key from Kalshi dashboard.")
        response = input("Continue anyway? (y/N): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    # Get environment
    print("\nSelect environment:")
    print("1. demo (default - paper trading)")
    print("2. prod (LIVE trading - real money)")
    env_choice = input("Choice (1/2) [1]: ").strip() or "1"
    
    if env_choice == "2":
        print("\n⚠️  WARNING: You selected PRODUCTION mode!")
        print("This will use REAL money on Kalshi!")
        confirm = input("Type 'PRODUCTION' to confirm: ")
        if confirm != "PRODUCTION":
            print("Production mode not confirmed. Using demo.")
            kalshi_env = "demo"
        else:
            kalshi_env = "prod"
    else:
        kalshi_env = "demo"
    
    # Create .env content
    env_content = f"""# Kalshi API Credentials
# Generated by setup_kalshi_creds.py
# Last updated: {Path(__file__).stat().st_mtime if Path(__file__).exists() else 'now'}

# Kalshi API Environment (demo or prod)
KALSHI_ENV={kalshi_env}

# Your Kalshi API Key ID (from https://kalshi.com → Settings → API Keys)
KALSHI_API_KEY_ID={key_id}

# Path to your Kalshi private key file (.pem)
KALSHI_PRIVATE_KEY_PATH={private_key_path}

# Alternative: Set the private key content directly (not recommended)
# KALSHI_PRIVATE_KEY_CONTENT=<paste key content here>

# MERID Trade Mode (backtest, paper, or live)
MERID_TRADE_MODE=paper

# Optional: Set explicit capital (will override Kalshi balance fetch)
# MERID_TOTAL_CAPITAL_USD=1400

# Optional: Redis URL (if not using default)
# REDIS_URL=redis://localhost:6379/0
"""
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ Created {env_file.absolute()}")
    print(f"\nEnvironment: {kalshi_env.upper()}")
    print(f"Key ID: {key_id[:10]}..." if len(key_id) > 10 else f"Key ID: {key_id}")
    print(f"Private Key: {private_key_path}")
    
    print("\n" + "=" * 60)
    print("Next steps:")
    print("=" * 60)
    print("1. Review the .env file:")
    print("   cat .env")
    print()
    print("2. Test the credentials:")
    print("   python -c \"from merid.settings import settings; print(f'Balance: ${settings.total_capital_usd}')\"")
    print()
    print("3. Start the server:")
    print("   py -m uvicorn web.main:app --host 0.0.0.0 --port 8011")
    print()
    
    if kalshi_env == "demo":
        print("ℹ️  Running in DEMO mode - trades are simulated")
    else:
        print("⚠️  Running in PRODUCTION mode - trades use REAL money!")
    
    print("\n🎉 Setup complete!")

if __name__ == "__main__":
    main()
