"""
Automated governance proposal generation.

Transforms protocol health findings or strategy ideas into governance proposals
with templated actions, rationale, and impact summaries.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List
from datetime import datetime


@dataclass
class ProposalTrigger:
    trigger_id: str
    category: str
    summary: str
    data: Dict[str, str]


@dataclass
class ProposalDraft:
    proposal_id: str
    title: str
    description: str
    actions: List[Dict[str, str]]
    risk_assessment: str
    created_at: datetime = field(default_factory=datetime.utcnow)


class AutomatedProposalGenerator:
    def __init__(self) -> None:
        self._history: List[ProposalDraft] = []

    def generate(self, trigger: ProposalTrigger) -> ProposalDraft:
        title = f"{trigger.category.title()} Update - {trigger.trigger_id}"
        description = f"Autogenerated proposal to address: {trigger.summary}"
        actions = [{"type": trigger.category, "details": trigger.data}]
        draft = ProposalDraft(
            proposal_id=f"prop_{len(self._history) + 1}",
            title=title,
            description=description,
            actions=actions,
            risk_assessment="Low" if trigger.category == "parameter" else "Medium",
        )
        self._history.append(draft)
        return draft

    def recent(self, limit: int = 5) -> List[ProposalDraft]:
        return self._history[-limit:]
