"""
MERID MARL - QMIX (Monotonic Value Function Factorization)

QMIX factorizes the joint action-value function as a monotonic combination
of per-agent utilities:
- Q_tot = f(Q_1, Q_2, ..., Q_n) where f is monotonic in each Q_i
- Monotonicity ensures: argmax Q_tot = (argmax Q_1, ..., argmax Q_n)
- Mixing network weights are generated by hypernetworks conditioned on state

Reference: Rashid et al., "QMIX: Monotonic Value Function Factorisation for Deep Multi-Agent Reinforcement Learning"
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple
import numpy as np

from learning.marl.base import (
    MARLAgent,
    MARLCritic,
    Trajectory,
    Experience,
    ReplayBuffer,
    NeuralNetwork,
    QCritic,
    AgentRole,
)
from utils.logger import get_logger

logger = get_logger("learning.marl.qmix")


@dataclass
class QMIXConfig:
    """Configuration for QMIX algorithm."""
    # Learning rate
    lr: float = 5e-4
    
    # Discount
    gamma: float = 0.99
    
    # Target network
    target_update_interval: int = 200
    tau: float = 0.005  # Soft update coefficient
    
    # Exploration
    epsilon_start: float = 1.0
    epsilon_end: float = 0.05
    epsilon_decay_steps: int = 50000
    
    # Training
    batch_size: int = 32
    buffer_size: int = 50000
    
    # Architecture
    hidden_dims: List[int] = field(default_factory=lambda: [64, 64])
    mixing_embed_dim: int = 32
    hypernet_embed_dim: int = 64
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "lr": self.lr,
            "gamma": self.gamma,
            "target_update_interval": self.target_update_interval,
            "epsilon_start": self.epsilon_start,
            "epsilon_end": self.epsilon_end,
            "batch_size": self.batch_size,
        }


class QMIXAgent(MARLAgent):
    """QMIX agent with individual Q-network."""
    
    def __init__(
        self,
        agent_id: str,
        agent_idx: int,
        state_dim: int,
        action_dim: int,
        config: QMIXConfig,
    ):
        super().__init__(agent_id, state_dim, action_dim, AgentRole.ACTOR)
        
        self.agent_idx = agent_idx
        self.config = config
        
        # Q-network
        self.q_network = QCritic(state_dim, action_dim, config.hidden_dims)
        
        # Target Q-network
        self.target_q_network = QCritic(state_dim, action_dim, config.hidden_dims)
        self._sync_target()
        
        # Exploration
        self._epsilon = config.epsilon_start
        self._step_count = 0
    
    def _sync_target(self) -> None:
        """Sync target network with main network."""
        self.target_q_network.set_parameters(self.q_network.get_parameters())
    
    def soft_update_target(self) -> None:
        """Soft update target network."""
        main_params = self.q_network.get_parameters()
        target_params = self.target_q_network.get_parameters()
        
        for key in main_params:
            target_params[key] = (
                self.config.tau * main_params[key] +
                (1 - self.config.tau) * target_params[key]
            )
        
        self.target_q_network.set_parameters(target_params)
    
    def get_action(self, state: np.ndarray, deterministic: bool = False) -> Tuple[int, float]:
        """Get action using epsilon-greedy."""
        self._step_count += 1
        
        # Decay epsilon
        decay_progress = min(1.0, self._step_count / self.config.epsilon_decay_steps)
        self._epsilon = (
            self.config.epsilon_start +
            (self.config.epsilon_end - self.config.epsilon_start) * decay_progress
        )
        
        if not deterministic and np.random.random() < self._epsilon:
            action = np.random.randint(0, self.action_dim)
            return action, 0.0
        
        q_values = self.q_network.forward(state)
        action = int(np.argmax(q_values))
        
        return action, float(q_values[action])
    
    def get_q_values(self, state: np.ndarray) -> np.ndarray:
        """Get Q-values for all actions."""
        return self.q_network.forward(state)
    
    def get_target_q_values(self, state: np.ndarray) -> np.ndarray:
        """Get target Q-values for all actions."""
        return self.target_q_network.forward(state)


class MixingNetwork:
    """
    QMIX mixing network that combines individual Q-values monotonically.
    
    Uses hypernetworks to generate mixing weights conditioned on global state.
    """
    
    def __init__(
        self,
        n_agents: int,
        global_state_dim: int,
        embed_dim: int = 32,
        hypernet_embed_dim: int = 64,
    ):
        self.n_agents = n_agents
        self.global_state_dim = global_state_dim
        self.embed_dim = embed_dim
        
        # Hypernetwork for first layer weights
        self.hyper_w1 = NeuralNetwork(
            global_state_dim, n_agents * embed_dim, [hypernet_embed_dim]
        )
        
        # Hypernetwork for first layer bias
        self.hyper_b1 = NeuralNetwork(
            global_state_dim, embed_dim, [hypernet_embed_dim]
        )
        
        # Hypernetwork for second layer weights
        self.hyper_w2 = NeuralNetwork(
            global_state_dim, embed_dim, [hypernet_embed_dim]
        )
        
        # Hypernetwork for second layer bias (scalar output)
        self.hyper_b2 = NeuralNetwork(
            global_state_dim, 1, [hypernet_embed_dim]
        )
    
    def forward(
        self,
        agent_q_values: np.ndarray,
        global_state: np.ndarray,
    ) -> float:
        """
        Combine agent Q-values using state-conditioned mixing.
        
        agent_q_values: (n_agents,) array of individual Q-values
        global_state: global state for conditioning
        
        Returns: Q_tot scalar
        """
        # Generate mixing weights (ensure non-negative for monotonicity)
        w1 = np.abs(self.hyper_w1.forward(global_state)).reshape(self.n_agents, self.embed_dim)
        b1 = self.hyper_b1.forward(global_state)
        
        w2 = np.abs(self.hyper_w2.forward(global_state)).reshape(self.embed_dim, 1)
        b2 = self.hyper_b2.forward(global_state)
        
        # First layer: (n_agents,) @ (n_agents, embed_dim) + (embed_dim,) -> (embed_dim,)
        hidden = np.dot(agent_q_values, w1) + b1
        hidden = np.maximum(0, hidden)  # ELU activation (simplified to ReLU)
        
        # Second layer: (embed_dim,) @ (embed_dim, 1) + (1,) -> scalar
        q_tot = np.dot(hidden, w2).squeeze() + b2.squeeze()
        
        return float(q_tot)
    
    def get_parameters(self) -> Dict[str, np.ndarray]:
        """Get all hypernetwork parameters."""
        params = {}
        for name, net in [
            ("hyper_w1", self.hyper_w1),
            ("hyper_b1", self.hyper_b1),
            ("hyper_w2", self.hyper_w2),
            ("hyper_b2", self.hyper_b2),
        ]:
            net_params = net.get_parameters()
            for key, value in net_params.items():
                params[f"{name}_{key}"] = value
        return params
    
    def set_parameters(self, params: Dict[str, np.ndarray]) -> None:
        """Set all hypernetwork parameters."""
        for name, net in [
            ("hyper_w1", self.hyper_w1),
            ("hyper_b1", self.hyper_b1),
            ("hyper_w2", self.hyper_w2),
            ("hyper_b2", self.hyper_b2),
        ]:
            net_params = {}
            for key in net.get_parameters().keys():
                full_key = f"{name}_{key}"
                if full_key in params:
                    net_params[key] = params[full_key]
            if net_params:
                net.set_parameters(net_params)


class QMIX:
    """
    QMIX: Monotonic Value Function Factorisation.
    
    Key features:
    - Per-agent Q-networks for decentralized execution
    - Mixing network for centralized training
    - Monotonic factorization ensures consistent greedy action selection
    """
    
    def __init__(
        self,
        n_agents: int,
        state_dim: int,
        action_dim: int,
        global_state_dim: int,
        config: Optional[QMIXConfig] = None,
    ):
        self.n_agents = n_agents
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.global_state_dim = global_state_dim
        self.config = config or QMIXConfig()
        
        # Initialize agents
        self.agents: Dict[str, QMIXAgent] = {}
        for i in range(n_agents):
            agent_id = f"qmix_agent_{i}"
            self.agents[agent_id] = QMIXAgent(
                agent_id, i, state_dim, action_dim, self.config
            )
        
        # Mixing network
        self.mixer = MixingNetwork(
            n_agents, global_state_dim,
            self.config.mixing_embed_dim,
            self.config.hypernet_embed_dim,
        )
        
        # Target mixing network
        self.target_mixer = MixingNetwork(
            n_agents, global_state_dim,
            self.config.mixing_embed_dim,
            self.config.hypernet_embed_dim,
        )
        self._sync_target_mixer()
        
        # Replay buffer
        self.buffer = ReplayBuffer(self.config.buffer_size)
        
        # Training statistics
        self._update_count = 0
        self._losses: List[float] = []
        
        logger.info(
            "QMIX initialized: %d agents, state_dim=%d, action_dim=%d",
            n_agents, state_dim, action_dim
        )
    
    def _sync_target_mixer(self) -> None:
        """Sync target mixer with main mixer."""
        self.target_mixer.set_parameters(self.mixer.get_parameters())
    
    def get_actions(
        self,
        observations: Dict[str, np.ndarray],
        deterministic: bool = False,
    ) -> Dict[str, Tuple[int, float]]:
        """Get actions for all agents."""
        actions = {}
        for agent_id, obs in observations.items():
            if agent_id in self.agents:
                actions[agent_id] = self.agents[agent_id].get_action(obs, deterministic)
        return actions
    
    def store_transition(
        self,
        observations: Dict[str, np.ndarray],
        actions: Dict[str, int],
        rewards: Dict[str, float],
        next_observations: Dict[str, np.ndarray],
        dones: Dict[str, bool],
        global_state: np.ndarray,
        next_global_state: np.ndarray,
    ) -> None:
        """Store transition in replay buffer."""
        # Store as joint experience
        for agent_id in self.agents:
            if agent_id in observations:
                exp = Experience(
                    state=observations[agent_id],
                    action=actions.get(agent_id, 0),
                    reward=sum(rewards.values()) / len(rewards),  # Shared reward
                    next_state=next_observations.get(agent_id, observations[agent_id]),
                    done=any(dones.values()),
                    agent_id=agent_id,
                    global_state=global_state,
                    other_actions={k: v for k, v in actions.items() if k != agent_id},
                    info={
                        "next_global_state": next_global_state,
                        "all_actions": actions,
                        "all_rewards": rewards,
                    },
                )
                self.buffer.add(exp)
    
    def update(self) -> Dict[str, Any]:
        """Update all networks using sampled batch."""
        if len(self.buffer) < self.config.batch_size:
            return {"update_count": self._update_count, "loss": 0.0}
        
        self._update_count += 1
        
        # Sample batch
        batch = self.buffer.sample(self.config.batch_size)
        
        # Compute loss and update
        loss = self._compute_and_update(batch)
        self._losses.append(loss)
        
        # Update target networks
        if self._update_count % self.config.target_update_interval == 0:
            self._sync_target_mixer()
            for agent in self.agents.values():
                agent._sync_target()
        else:
            # Soft update
            for agent in self.agents.values():
                agent.soft_update_target()
        
        return {
            "update_count": self._update_count,
            "loss": loss,
            "epsilon": list(self.agents.values())[0]._epsilon if self.agents else 0,
        }
    
    def _compute_and_update(self, batch: List[Experience]) -> float:
        """Compute QMIX loss and update networks."""
        total_loss = 0.0
        
        for exp in batch:
            # Get current Q-values for each agent
            agent_q_values = np.zeros(self.n_agents)
            agent_target_q_values = np.zeros(self.n_agents)
            
            for i, (agent_id, agent) in enumerate(self.agents.items()):
                # Current Q-value for taken action
                q_values = agent.get_q_values(exp.state)
                action = exp.info["all_actions"].get(agent_id, 0)
                agent_q_values[i] = q_values[action]
                
                # Target Q-value (max over actions)
                target_q_values = agent.get_target_q_values(exp.next_state)
                agent_target_q_values[i] = np.max(target_q_values)
            
            # Mix Q-values
            q_tot = self.mixer.forward(agent_q_values, exp.global_state)
            
            # Target Q_tot
            next_global_state = exp.info.get("next_global_state", exp.global_state)
            target_q_tot = self.target_mixer.forward(agent_target_q_values, next_global_state)
            
            # TD target
            if exp.done:
                td_target = exp.reward
            else:
                td_target = exp.reward + self.config.gamma * target_q_tot
            
            # TD error
            td_error = td_target - q_tot
            total_loss += td_error ** 2
        
        loss = total_loss / len(batch)
        
        # Update agent Q-networks
        for agent in self.agents.values():
            self._update_agent_q_network(agent, batch, loss)
        
        # Update mixer
        self._update_mixer(batch)
        
        return loss
    
    def _update_agent_q_network(
        self,
        agent: QMIXAgent,
        batch: List[Experience],
        loss: float,
    ) -> None:
        """Update agent's Q-network."""
        params = agent.q_network.get_parameters()
        epsilon = 1e-4
        
        for key in params:
            grad = np.zeros_like(params[key])
            n_samples = min(5, params[key].size)
            indices = np.random.choice(params[key].size, n_samples, replace=False)
            
            for idx in indices:
                flat_idx = np.unravel_index(idx, params[key].shape)
                
                params[key][flat_idx] += epsilon
                agent.q_network.set_parameters(params)
                loss_plus = self._compute_batch_loss(batch)
                
                params[key][flat_idx] -= 2 * epsilon
                agent.q_network.set_parameters(params)
                loss_minus = self._compute_batch_loss(batch)
                
                params[key][flat_idx] += epsilon
                grad[flat_idx] = (loss_plus - loss_minus) / (2 * epsilon)
            
            params[key] -= self.config.lr * grad
        
        agent.q_network.set_parameters(params)
    
    def _update_mixer(self, batch: List[Experience]) -> None:
        """Update mixing network."""
        params = self.mixer.get_parameters()
        epsilon = 1e-4
        
        for key in params:
            grad = np.zeros_like(params[key])
            n_samples = min(3, params[key].size)
            indices = np.random.choice(params[key].size, n_samples, replace=False)
            
            for idx in indices:
                flat_idx = np.unravel_index(idx, params[key].shape)
                
                params[key][flat_idx] += epsilon
                self.mixer.set_parameters(params)
                loss_plus = self._compute_batch_loss(batch)
                
                params[key][flat_idx] -= 2 * epsilon
                self.mixer.set_parameters(params)
                loss_minus = self._compute_batch_loss(batch)
                
                params[key][flat_idx] += epsilon
                grad[flat_idx] = (loss_plus - loss_minus) / (2 * epsilon)
            
            params[key] -= self.config.lr * grad
        
        self.mixer.set_parameters(params)
    
    def _compute_batch_loss(self, batch: List[Experience]) -> float:
        """Compute loss for a batch."""
        total_loss = 0.0
        
        for exp in batch:
            agent_q_values = np.zeros(self.n_agents)
            agent_target_q_values = np.zeros(self.n_agents)
            
            for i, (agent_id, agent) in enumerate(self.agents.items()):
                q_values = agent.get_q_values(exp.state)
                action = exp.info["all_actions"].get(agent_id, 0)
                agent_q_values[i] = q_values[action]
                
                target_q_values = agent.get_target_q_values(exp.next_state)
                agent_target_q_values[i] = np.max(target_q_values)
            
            q_tot = self.mixer.forward(agent_q_values, exp.global_state)
            
            next_global_state = exp.info.get("next_global_state", exp.global_state)
            target_q_tot = self.target_mixer.forward(agent_target_q_values, next_global_state)
            
            if exp.done:
                td_target = exp.reward
            else:
                td_target = exp.reward + self.config.gamma * target_q_tot
            
            total_loss += (td_target - q_tot) ** 2
        
        return total_loss / len(batch)
    
    def get_stats(self) -> Dict[str, Any]:
        """Get training statistics."""
        return {
            "n_agents": self.n_agents,
            "update_count": self._update_count,
            "buffer_size": len(self.buffer),
            "avg_loss": np.mean(self._losses[-100:]) if self._losses else 0,
            "epsilon": list(self.agents.values())[0]._epsilon if self.agents else 0,
        }
