/**
 * UI Views Manifest — AUTO-GENERATED from merid/ui_views_manifest.py
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run: python scripts/generate_ts_manifest.py
 */

export interface ApiBinding {
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
  pollingMs: number;
  required: boolean;
}

export interface ComponentBinding {
  name: string;
  apis: ApiBinding[];
}

export type ViewSection = "navigation" | "management" | "system";

export interface ViewConfig {
  id: string;
  route: string;
  title: string;
  section: ViewSection;
  domain?: string;
  kalshiOnly: boolean;
  components: ComponentBinding[];
}

export const VIEWS: ViewConfig[] = [
  {
    id: "overview", route: "overview", title: "Overview", section: "navigation", kalshiOnly: true,
    components: [
    { name: "PortfolioSummary", apis: [{ method: "GET", path: "/api/v1/portfolio/summary", pollingMs: 5000, required: true }] },
    { name: "PositionsList", apis: [{ method: "GET", path: "/api/v1/positions", pollingMs: 2000, required: true }] },
    { name: "RecentOrders", apis: [{ method: "GET", path: "/api/v1/orders", pollingMs: 1000, required: true }] },
    ],
  },
  {
    id: "wallet", route: "wallet", title: "Wallet", section: "navigation", kalshiOnly: false,
    components: [
    { name: "WalletBalances", apis: [{ method: "GET", path: "/api/v1/wallet/balances", pollingMs: 10000, required: true }] },
    ],
  },
  {
    id: "treasury", route: "treasury", title: "Treasury", section: "navigation", kalshiOnly: false,
    components: [
    { name: "TreasuryOverview", apis: [{ method: "GET", path: "/api/v1/treasury/overview", pollingMs: 30000, required: true }] },
    { name: "QuadraticFunding", apis: [{ method: "GET", path: "/api/v1/quadratic-funding", pollingMs: 0, required: false }] },
    ],
  },
  {
    id: "trading", route: "trading", title: "Live Trading", section: "navigation", domain: "crypto", kalshiOnly: false,
    components: [
    { name: "Positions", apis: [{ method: "GET", path: "/api/v1/positions", pollingMs: 2000, required: true }, { method: "GET", path: "/api/v1/positions/summary", pollingMs: 2000, required: true }] },
    { name: "Orders", apis: [{ method: "GET", path: "/api/v1/orders", pollingMs: 1000, required: true }, { method: "GET", path: "/api/v1/orders/summary", pollingMs: 1000, required: true }] },
    { name: "Fills", apis: [{ method: "GET", path: "/api/v1/fills", pollingMs: 1000, required: true }] },
    { name: "ConsensusSummary", apis: [{ method: "GET", path: "/api/v1/consensus/summary", pollingMs: 15000, required: true }] },
    ],
  },
  {
    id: "tradefloor", route: "tradefloor", title: "Trade Floor", section: "navigation", kalshiOnly: false,
    components: [
    { name: "TradeFloorStatus", apis: [{ method: "GET", path: "/api/v1/trade-floor/status", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/trade-floor/active-trades", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/trade-floor/signals", pollingMs: 0, required: true }] },
    { name: "RiskFallback", apis: [{ method: "GET", path: "/api/v1/risk/metrics", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/orders", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "positions", route: "positions", title: "Positions", section: "navigation", kalshiOnly: true,
    components: [
    { name: "PositionTable", apis: [{ method: "GET", path: "/api/v1/trading/portfolio/summary", pollingMs: 5000, required: true }] },
    ],
  },
  {
    id: "orders", route: "orders", title: "Orders", section: "navigation", kalshiOnly: false,
    components: [
    { name: "OrderTable", apis: [{ method: "GET", path: "/api/v1/trading/orders/open", pollingMs: 2000, required: true }] },
    ],
  },
  {
    id: "research", route: "research", title: "Research", section: "navigation", kalshiOnly: false,
    components: [
    { name: "BacktestResults", apis: [{ method: "GET", path: "/api/v1/research/backtest/results", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "predictions", route: "predictions", title: "Prediction Markets", section: "navigation", domain: "prediction", kalshiOnly: true,
    components: [
    { name: "USCompliantMarkets", apis: [{ method: "GET", path: "/api/v1/us-compliant/prediction-markets", pollingMs: 60000, required: true }] },
    { name: "PredictionSummary", apis: [{ method: "GET", path: "/api/v1/prediction-markets/summary", pollingMs: 60000, required: true }] },
    { name: "DriftSignals", apis: [{ method: "GET", path: "/api/v1/us-compliant/drift-signals?limit=30", pollingMs: 0, required: true }] },
    { name: "SpectatorMode", apis: [{ method: "GET", path: "/api/v1/trading-mode/spectator/live?limit=15", pollingMs: 0, required: true }, { method: "POST", path: "/api/v1/trading-mode/spectator/record", pollingMs: 0, required: false }] },
    ],
  },
  {
    id: "prediction-consensus", route: "prediction-consensus", title: "Prediction Consensus", section: "navigation", domain: "prediction", kalshiOnly: true,
    components: [
    { name: "ConsensusSummary", apis: [{ method: "GET", path: "/api/v1/prediction/consensus/summary", pollingMs: 15000, required: true }] },
    { name: "Opinions", apis: [{ method: "GET", path: "/api/v1/prediction/consensus/opinions", pollingMs: 0, required: true }] },
    { name: "Plans", apis: [{ method: "GET", path: "/api/v1/prediction/consensus/plans", pollingMs: 0, required: true }] },
    { name: "Instruments", apis: [{ method: "GET", path: "/api/v1/prediction/consensus/instruments", pollingMs: 0, required: true }] },
    { name: "Metrics", apis: [{ method: "GET", path: "/api/v1/prediction/metrics", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "betting", route: "betting", title: "Betting Markets", section: "navigation", domain: "betting", kalshiOnly: false,
    components: [
    { name: "BettingOverview", apis: [{ method: "GET", path: "/api/v1/betting/overview", pollingMs: 30000, required: false }] },
    { name: "BettingConsensus", apis: [{ method: "GET", path: "/api/v1/betting/consensus/summary", pollingMs: 30000, required: true }, { method: "GET", path: "/api/v1/betting/consensus/events", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "betting-consensus", route: "betting-consensus", title: "Swarm Betting", section: "navigation", domain: "betting", kalshiOnly: false,
    components: [
    { name: "ConsensusSummary", apis: [{ method: "GET", path: "/api/v1/betting/consensus/summary", pollingMs: 15000, required: true }] },
    { name: "LiveEvents", apis: [{ method: "GET", path: "/api/v1/betting/consensus/live", pollingMs: 0, required: true }] },
    { name: "Plans", apis: [{ method: "GET", path: "/api/v1/betting/consensus/plans", pollingMs: 0, required: true }] },
    { name: "Metrics", apis: [{ method: "GET", path: "/api/v1/betting/consensus/metrics", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "flow-radar", route: "flow-radar", title: "Flow Radar", section: "navigation", kalshiOnly: false,
    components: [
    { name: "FlowRadar", apis: [{ method: "GET", path: "/api/v1/flow/radar", pollingMs: 10000, required: true }, { method: "GET", path: "/api/v1/flow/tokens", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/flow/entities", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/flow/events", pollingMs: 0, required: true }] },
    { name: "FlowMetrics", apis: [{ method: "GET", path: "/api/v1/flow/metrics", pollingMs: 10000, required: true }, { method: "GET", path: "/api/v1/flow/risk", pollingMs: 0, required: true }] },
    { name: "SniperStatus", apis: [{ method: "GET", path: "/api/v1/flow/sniper/status", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/flow/sniper/fills", pollingMs: 0, required: true }] },
    { name: "FlowPlans", apis: [{ method: "GET", path: "/api/v1/flow/plans", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "signal-layer", route: "signal-layer", title: "Signal Layer", section: "navigation", kalshiOnly: true,
    components: [
    { name: "SignalArbs", apis: [{ method: "GET", path: "/api/v1/signal-layer/arbs", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/signal-layer/arb-plans", pollingMs: 0, required: true }] },
    { name: "SignalMetrics", apis: [{ method: "GET", path: "/api/v1/signal-layer/metrics", pollingMs: 30000, required: true }] },
    { name: "MacroSignals", apis: [{ method: "GET", path: "/api/v1/signal-layer/macro", pollingMs: 0, required: true }] },
    { name: "DriftSignals", apis: [{ method: "GET", path: "/api/v1/signal-layer/drift", pollingMs: 0, required: true }] },
    { name: "CQI", apis: [{ method: "GET", path: "/api/v1/signal-layer/cqi", pollingMs: 0, required: true }] },
    { name: "DecayConfigs", apis: [{ method: "GET", path: "/api/v1/signal-layer/decay-configs", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "rewards", route: "rewards", title: "Rewards", section: "navigation", kalshiOnly: false,
    components: [
    { name: "RewardsSummary", apis: [{ method: "GET", path: "/api/v1/rewards/summary", pollingMs: 0, required: true }] },
    { name: "Quests", apis: [{ method: "GET", path: "/api/v1/rewards/quests?season=1", pollingMs: 0, required: true }] },
    { name: "Leaderboard", apis: [{ method: "GET", path: "/api/v1/rewards/leaderboard?limit=20", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "social", route: "social", title: "Social Feed", section: "navigation", kalshiOnly: false,
    components: [
    { name: "SocialFeed", apis: [{ method: "GET", path: "/api/v1/social/feed", pollingMs: 30000, required: true }, { method: "POST", path: "/api/v1/social/post", pollingMs: 0, required: false }] },
    ],
  },
  {
    id: "operator", route: "operator", title: "Operator", section: "management", kalshiOnly: true,
    components: [
    { name: "OperatorSummary", apis: [{ method: "GET", path: "/api/operator/audit-trail", pollingMs: 0, required: true }, { method: "GET", path: "/api/operator/system/status", pollingMs: 0, required: true }] },
    { name: "ControlPlane", apis: [{ method: "POST", path: "/api/v1/monitoring/system/stop", pollingMs: 0, required: false }] },
    { name: "ActivityStream", apis: [{ method: "GET", path: "/api/v1/orders?limit=20", pollingMs: 0, required: true }, { method: "GET", path: "/api/v1/system/decisions/recent?limit=10", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "risk", route: "risk", title: "Risk & Health", section: "management", kalshiOnly: true,
    components: [
    { name: "RiskMetrics", apis: [{ method: "GET", path: "/api/v1/risk/metrics", pollingMs: 30000, required: true }] },
    { name: "RiskAlerts", apis: [{ method: "GET", path: "/api/v1/risk/alerts", pollingMs: 15000, required: true }] },
    { name: "SystemHealth", apis: [{ method: "GET", path: "/api/v1/system/health", pollingMs: 60000, required: true }] },
    { name: "PositionLimits", apis: [{ method: "GET", path: "/api/v1/risk/position-limits", pollingMs: 10000, required: true }] },
    ],
  },
  {
    id: "agents", route: "agents", title: "Bots/Agents", section: "management", kalshiOnly: false,
    components: [
    { name: "AgentFleet", apis: [{ method: "GET", path: "/api/v1/agents", pollingMs: 10000, required: true }] },
    { name: "AgentCharters", apis: [{ method: "GET", path: "/api/v1/charters", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "devswarm", route: "devswarm", title: "Dev Swarm", section: "management", kalshiOnly: false,
    components: [
    { name: "SwarmStatus", apis: [{ method: "GET", path: "/api/dev-swarm/status", pollingMs: 0, required: true }, { method: "GET", path: "/api/dev-swarm/agents", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "mining", route: "mining", title: "Mining", section: "management", kalshiOnly: false,
    components: [
    { name: "MiningOverview", apis: [{ method: "GET", path: "/api/v1/mining/overview", pollingMs: 60000, required: true }] },
    ],
  },
  {
    id: "institutional", route: "institutional", title: "Institutional", section: "management", kalshiOnly: false,
    components: [
    { name: "InstitutionalDashboard", apis: [{ method: "GET", path: "/api/v1/institutional/overview", pollingMs: 0, required: false }] },
    ],
  },
  {
    id: "plugins", route: "plugins", title: "Plugins", section: "management", kalshiOnly: false,
    components: [
    { name: "PluginList", apis: [{ method: "GET", path: "/api/v1/plugins/list", pollingMs: 0, required: true }, { method: "POST", path: "/api/v1/plugins/install/{pluginId}", pollingMs: 0, required: false }, { method: "DELETE", path: "/api/v1/plugins/uninstall/{pluginId}", pollingMs: 0, required: false }, { method: "POST", path: "/api/v1/plugins/toggle/{pluginId}", pollingMs: 0, required: false }] },
    ],
  },
  {
    id: "api", route: "api", title: "API Dashboard", section: "management", kalshiOnly: false,
    components: [
    { name: "ApiStatus", apis: [{ method: "GET", path: "/api/v1/api/status", pollingMs: 30000, required: true }] },
    { name: "ApiMetrics", apis: [{ method: "GET", path: "/api/v1/api/metrics", pollingMs: 30000, required: false }] },
    ],
  },
  {
    id: "analytics", route: "analytics", title: "Analytics", section: "management", kalshiOnly: false,
    components: [
    { name: "AnalyticsDashboard", apis: [{ method: "GET", path: "/api/v1/analytics/overview", pollingMs: 0, required: false }] },
    ],
  },
  {
    id: "settings", route: "settings", title: "Settings", section: "management", kalshiOnly: false,
    components: [
    { name: "UserProfile", apis: [{ method: "GET", path: "/api/v1/user/profile", pollingMs: 0, required: true }, { method: "PUT", path: "/api/v1/user/settings", pollingMs: 0, required: false }] },
    ],
  },
  {
    id: "health", route: "health", title: "System Health", section: "system", kalshiOnly: true,
    components: [
    { name: "HealthDashboard", apis: [{ method: "GET", path: "/api/v1/system/health", pollingMs: 60000, required: true }, { method: "GET", path: "/api/system/health", pollingMs: 0, required: true }, { method: "GET", path: "/api/system/version", pollingMs: 0, required: true }, { method: "GET", path: "/api/system/components", pollingMs: 0, required: true }] },
    ],
  },
  {
    id: "logs", route: "logs", title: "Logs", section: "system", kalshiOnly: false,
    components: [
    { name: "LogViewer", apis: [{ method: "GET", path: "/api/v1/logs", pollingMs: 5000, required: true }] },
    ],
  },
];


export function getView(viewId: string): ViewConfig | undefined {
  return VIEWS.find((v) => v.id === viewId);
}

export function viewsForSection(section: ViewSection): ViewConfig[] {
  return VIEWS.filter((v) => v.section === section);
}

export function viewsForDomain(domain: string): ViewConfig[] {
  return VIEWS.filter((v) => v.domain === domain);
}

export function kalshiOnlyViews(): ViewConfig[] {
  return VIEWS.filter((v) => v.kalshiOnly);
}

export function allApiPaths(): string[] {
  const paths = new Set<string>();
  for (const v of VIEWS) {
    for (const c of v.components) {
      for (const a of c.apis) {
        if (a.method === "GET") paths.add(a.path);
      }
    }
  }
  return Array.from(paths).sort();
}
