"""Kalshi venue package for MERID."""

from merid.event_venues.kalshi.client import (
    KalshiVenueClient,
    KalshiSessionError,
    KalshiBusinessError,
    KalshiBusinessReject,
    KalshiTokenBucket,
    KALSHI_RATE_TIERS,
    KALSHI_REJECT_REASONS,
    KALSHI_BUSINESS_REJECT_CAUSES,
    parse_fix,
    handle_fix_reject,
    get_kalshi_client,
)
from merid.event_venues.kalshi.models import (
    KalshiBalance,
    KalshiConfig,
    KalshiMarket,
    KalshiOrder,
    KalshiOrderBook,
    KalshiOutcome,
    KalshiPosition,
    KalshiTrade,
)
from merid.event_venues.kalshi.trading import KalshiTrader
from merid.event_venues.kalshi.ws import KalshiWebSocket
from merid.event_venues.kalshi.market_catalog import (
    KalshiMarketCatalog,
    CatalogMarket,
    CatalogSnapshot,
    get_market_catalog,
)
from merid.event_venues.kalshi.kalshi_risk import (
    KalshiRiskManager,
    KalshiRiskConfig,
    kalshi_fee_cents,
    kelly_size_kalshi,
    dynamic_position_sizes,
    multi_market_kelly_sizes,
    get_kalshi_risk,
    edge_from_prediction,
    kelly_size_from_kalman,
    get_live_bankroll,
    get_live_bankroll_async,
)
# LEGACY: Old bankroll service moved to legacy/
# Use bankroll_service_v2 instead
# from merid.event_venues.kalshi.legacy.bankroll_service import ...

# NEW v2 modules - preferred
from merid.event_venues.kalshi.types import (
    BalanceState,
    RawVenueBalance,
    InternalBankroll,
    BalanceSuccess,
    BalanceTemporaryError,
    BalancePermanentError,
    BalanceResult,
)
from merid.event_venues.kalshi.client_v2 import KalshiClientV2
from merid.event_venues.kalshi.bankroll_service_v2 import (
    BankrollServiceV2,
    BankrollSummary,
    get_bankroll_service,
    get_equity_for_risk_calc_sync,
    get_summary_sync,
)
from merid.event_venues.kalshi.signal_router import (
    AgentSignal,
    SignalRouter,
    get_signal_router,
    subscribe_to_signals,
    submit_signal,
)
from merid.event_venues.kalshi.risk_policy import (
    KalshiRiskPolicy,
    RiskAllowance,
    get_default_policy,
    check_trade_allowed,
)
from merid.event_venues.kalshi.ws_bridge import (
    KalshiWebSocketBridge,
    get_ws_bridge,
)
from merid.event_venues.kalshi.backtest import (
    MarketSnapshot,
    TradeDecision,
    BacktestState,
    PriceCandle,
    backtest,
    backtest_summary,
    backtest_kalman_strategy,
)
from merid.event_venues.kalshi.volume_monitor import (
    VolumeMonitor,
    get_volume_monitor,
    make_telegram_sink,
    make_discord_sink,
    Kalman1D,
    PriceKalman,
    tune_kalman_params,
    KALSHI_ADVANCED_API_FORM,
)
from merid.event_venues.kalshi.trade_analytics import (
    compute_vwap,
    detect_large_trades,
)
from merid.event_venues.kalshi.order_router import (
    OrderIntent,
    OrderResult,
    route_order,
    simulate_paper_fill,
    KALSHI_CHANNEL_PRICE,
    KALSHI_CHANNEL_TRADE,
    KALSHI_CHANNEL_ORDERBOOK,
    KALSHI_CHANNEL_ORDER_FILL,
    KALSHI_CHANNEL_ORDER_REJECT,
)
from merid.event_venues.kalshi.crypto_series import (
    list_crypto_series,
    fetch_markets_batch,
    CRYPTO_FREQUENCIES,
    CRYPTO_SERIES_PREFIXES,
    FREQUENCY_SUFFIXES,
    CryptoSeries,
    MarketInfo,
    invalidate_crypto_series_cache,
    get_cache_stats,
)

__all__ = [
    # Core v1 client
    "KalshiVenueClient",
    "KalshiSessionError",
    "KalshiBusinessError",
    "KalshiTokenBucket",
    "KALSHI_RATE_TIERS",
    "KalshiBusinessReject",
    "KalshiWebSocket",
    "KalshiTrader",
    "get_kalshi_client",
    "KalshiConfig",
    "KalshiMarket",
    "KalshiOutcome",
    "KalshiOrder",
    "KalshiOrderBook",
    "KalshiPosition",
    "KalshiTrade",
    "KalshiBalance",
    "KalshiMarketCatalog",
    "CatalogMarket",
    "CatalogSnapshot",
    "get_market_catalog",
    "KalshiRiskManager",
    "KalshiRiskConfig",
    "kalshi_fee_cents",
    "kelly_size_kalshi",
    "dynamic_position_sizes",
    "multi_market_kelly_sizes",
    "get_kalshi_risk",
    "get_live_bankroll",
    "get_live_bankroll_async",
    "KalshiWebSocketBridge",
    "get_ws_bridge",
    "MarketSnapshot",
    "TradeDecision",
    "BacktestState",
    "backtest",
    "backtest_summary",
    "VolumeMonitor",
    "get_volume_monitor",
    "make_telegram_sink",
    "make_discord_sink",
    "Kalman1D",
    "PriceKalman",
    "KALSHI_ADVANCED_API_FORM",
    "KALSHI_REJECT_REASONS",
    "KALSHI_BUSINESS_REJECT_CAUSES",
    "parse_fix",
    "handle_fix_reject",
    "tune_kalman_params",
    "compute_vwap",
    "detect_large_trades",
    "edge_from_prediction",
    "kelly_size_from_kalman",
    "PriceCandle",
    "backtest_kalman_strategy",
    "OrderIntent",
    "OrderResult",
    "route_order",
    "simulate_paper_fill",
    "KALSHI_CHANNEL_PRICE",
    "KALSHI_CHANNEL_TRADE",
    "KALSHI_CHANNEL_ORDERBOOK",
    "KALSHI_CHANNEL_ORDER_FILL",
    "KALSHI_CHANNEL_ORDER_REJECT",
    "list_crypto_series",
    "fetch_markets_batch",
    "CRYPTO_FREQUENCIES",
    "CRYPTO_SERIES_PREFIXES",
    "FREQUENCY_SUFFIXES",
    "CryptoSeries",
    "MarketInfo",
    "invalidate_crypto_series_cache",
    "get_cache_stats",
    # NEW v2 modules
    "BalanceState",
    "RawVenueBalance",
    "InternalBankroll",
    "BalanceSuccess",
    "BalanceTemporaryError",
    "BalancePermanentError",
    "BalanceResult",
    "KalshiClientV2",
    "BankrollServiceV2",
    "BankrollSummary",
    "get_equity_for_risk_calc_sync",
    "get_summary_sync",
    "AgentSignal",
    "SignalRouter",
    "get_signal_router",
    "subscribe_to_signals",
    "submit_signal",
    "KalshiRiskPolicy",
    "RiskAllowance",
    "get_default_policy",
    "check_trade_allowed",
]
