"""Generate TypeScript UI views manifest from the Python source of truth.

Usage:
  python scripts/generate_ts_manifest.py          # write to web/react/src/config/uiViewsManifest.ts
  python scripts/generate_ts_manifest.py --check   # exit 1 if TS file is out of date
  python scripts/generate_ts_manifest.py --stdout   # print to stdout instead of writing

The Python manifest (merid/ui_views_manifest.py) is canonical.
This script ensures the TypeScript mirror never diverges.
"""

import json
import os
import sys

# Ensure project root is on path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from merid.ui_views_manifest import VIEWS  # noqa: E402

TS_OUTPUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "web", "react", "src", "config", "uiViewsManifest.ts",
)

HEADER = '''/**
 * UI Views Manifest — AUTO-GENERATED from merid/ui_views_manifest.py
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run: python scripts/generate_ts_manifest.py
 */

export interface ApiBinding {
  method: "GET" | "POST" | "PUT" | "DELETE";
  path: string;
  pollingMs: number;
  required: boolean;
}

export interface ComponentBinding {
  name: string;
  apis: ApiBinding[];
}

export type ViewSection = "navigation" | "management" | "system";

export interface ViewConfig {
  id: string;
  route: string;
  title: string;
  section: ViewSection;
  domain?: string;
  kalshiOnly: boolean;
  components: ComponentBinding[];
}
'''


def _view_to_ts(view) -> dict:
    """Convert a Python ViewConfig to a JSON-serializable dict."""
    return {
        "id": view.id,
        "route": view.route,
        "title": view.title,
        "section": view.section,
        "domain": view.domain,
        "kalshiOnly": view.kalshi_only,
        "components": [
            {
                "name": c.name,
                "apis": [
                    {
                        "method": a.method,
                        "path": a.path,
                        "pollingMs": a.polling_ms,
                        "required": a.required,
                    }
                    for a in c.apis
                ],
            }
            for c in view.components
        ],
    }


def _format_api(a: dict) -> str:
    parts = [f'method: "{a["method"]}"', f'path: "{a["path"]}"']
    parts.append(f'pollingMs: {a["pollingMs"]}')
    parts.append(f'required: {"true" if a["required"] else "false"}')
    return "{ " + ", ".join(parts) + " }"


def _format_component(c: dict) -> str:
    apis = ", ".join(_format_api(a) for a in c["apis"])
    return f'    {{ name: "{c["name"]}", apis: [{apis}] }}'


def _format_view(v: dict) -> str:
    lines = ["  {"]
    domain_str = f', domain: "{v["domain"]}"' if v["domain"] else ""
    kalshi_str = "true" if v["kalshiOnly"] else "false"
    lines.append(
        f'    id: "{v["id"]}", route: "{v["route"]}", '
        f'title: "{v["title"]}", section: "{v["section"]}"{domain_str}, '
        f'kalshiOnly: {kalshi_str},'
    )
    lines.append("    components: [")
    for c in v["components"]:
        lines.append(_format_component(c) + ",")
    lines.append("    ],")
    lines.append("  }")
    return "\n".join(lines)


def generate() -> str:
    """Generate the full TypeScript file content."""
    views_data = [_view_to_ts(v) for v in VIEWS]

    parts = [HEADER]
    parts.append("export const VIEWS: ViewConfig[] = [")
    for v in views_data:
        parts.append(_format_view(v) + ",")
    parts.append("];\n")

    # Helpers
    parts.append("""
export function getView(viewId: string): ViewConfig | undefined {
  return VIEWS.find((v) => v.id === viewId);
}

export function viewsForSection(section: ViewSection): ViewConfig[] {
  return VIEWS.filter((v) => v.section === section);
}

export function viewsForDomain(domain: string): ViewConfig[] {
  return VIEWS.filter((v) => v.domain === domain);
}

export function kalshiOnlyViews(): ViewConfig[] {
  return VIEWS.filter((v) => v.kalshiOnly);
}

export function allApiPaths(): string[] {
  const paths = new Set<string>();
  for (const v of VIEWS) {
    for (const c of v.components) {
      for (const a of c.apis) {
        if (a.method === "GET") paths.add(a.path);
      }
    }
  }
  return Array.from(paths).sort();
}
""")

    return "\n".join(parts)


if __name__ == "__main__":
    content = generate()

    if "--stdout" in sys.argv:
        print(content)
        sys.exit(0)

    if "--check" in sys.argv:
        if not os.path.exists(TS_OUTPUT):
            print(f"FAIL: {TS_OUTPUT} does not exist")
            sys.exit(1)
        with open(TS_OUTPUT, "r", encoding="utf-8") as f:
            existing = f.read()
        if existing.strip() == content.strip():
            print("OK: TypeScript manifest is up to date")
            sys.exit(0)
        else:
            print(f"FAIL: {TS_OUTPUT} is out of date. Run: python scripts/generate_ts_manifest.py")
            sys.exit(1)

    os.makedirs(os.path.dirname(TS_OUTPUT), exist_ok=True)
    with open(TS_OUTPUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated {TS_OUTPUT}")
    print(f"  {len(VIEWS)} views written")
