"""
Prometheus Metrics Schema for 15m Pipeline Observability

Defines metrics that map directly to PipelineObservability fields for
Grafana dashboards and alerting.

Metric Naming Convention:
- merid_pipeline_<metric_name> for pipeline-level metrics
- merid_feature_<metric_name> for feature namespace metrics
- merid_risk_<metric_name> for risk check metrics
- merid_execution_<metric_name> for execution metrics

Labels:
- asset: BTC, ETH, SOL, XRP, DOGE
- pipeline_id: btc_15m_pipeline, eth_15m_pipeline, etc.
- namespace: ts_15m, sentiment, regime, etc.
- agent_name: Specific agent name
- decision_side: yes, no, none
- risk_check_name: max_size, asset_exposure, etc.
"""

from prometheus_client import Counter, Histogram, Gauge, Summary
from typing import Dict, Any
import time

# Pipeline-Level Metrics
pipeline_decisions_total = Counter(
    'merid_pipeline_decisions_total',
    'Total number of decisions generated by pipeline',
    ['asset', 'pipeline_id', 'decision_side']
)

pipeline_decisions_confidence = Histogram(
    'merid_pipeline_decisions_confidence',
    'Distribution of decision confidence scores',
    ['asset', 'pipeline_id'],
    buckets=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
)

pipeline_decisions_edge_estimate = Histogram(
    'merid_pipeline_decisions_edge_estimate',
    'Distribution of edge estimates',
    ['asset', 'pipeline_id'],
    buckets=[-1.0, -0.5, -0.25, -0.1, 0.0, 0.1, 0.25, 0.5, 1.0]
)

pipeline_decisions_size_pct = Histogram(
    'merid_pipeline_decisions_size_pct',
    'Distribution of position size percentages',
    ['asset', 'pipeline_id'],
    buckets=[0.0, 0.005, 0.01, 0.015, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2]
)

pipeline_cycles_total = Counter(
    'merid_pipeline_cycles_total',
    'Total number of pipeline cycles executed',
    ['asset', 'pipeline_id']
)

pipeline_cycles_errors = Counter(
    'merid_pipeline_cycles_errors',
    'Total number of pipeline cycle errors',
    ['asset', 'pipeline_id', 'error_type']
)

pipeline_success_rate = Gauge(
    'merid_pipeline_success_rate',
    'Pipeline success rate (decisions / cycles)',
    ['asset', 'pipeline_id']
)

# Timing Metrics
pipeline_feature_build_duration_seconds = Histogram(
    'merid_pipeline_feature_build_duration_seconds',
    'Time to build feature bundle',
    ['asset', 'pipeline_id'],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0]
)

pipeline_decision_duration_seconds = Histogram(
    'merid_pipeline_decision_duration_seconds',
    'Time for execution agent to make decision',
    ['asset', 'pipeline_id'],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0]
)

pipeline_risk_check_duration_seconds = Histogram(
    'merid_pipeline_risk_check_duration_seconds',
    'Time for pre-trade risk checks',
    ['asset', 'pipeline_id'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1]
)

pipeline_execution_duration_seconds = Histogram(
    'merid_pipeline_execution_duration_seconds',
    'Time to execute order',
    ['asset', 'pipeline_id'],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0]
)

pipeline_total_duration_seconds = Histogram(
    'merid_pipeline_total_duration_seconds',
    'Total pipeline end-to-end duration',
    ['asset', 'pipeline_id'],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
)

# Feature Namespace Metrics
feature_namespace_feature_count = Gauge(
    'merid_feature_namespace_feature_count',
    'Number of features per namespace',
    ['asset', 'pipeline_id', 'namespace']
)

feature_namespace_mean_value = Gauge(
    'merid_feature_namespace_mean_value',
    'Mean value of features in namespace',
    ['asset', 'pipeline_id', 'namespace']
)

feature_namespace_std_value = Gauge(
    'merid_feature_namespace_std_value',
    'Standard deviation of features in namespace',
    ['asset', 'pipeline_id', 'namespace']
)

feature_namespace_missing_count = Gauge(
    'merid_feature_namespace_missing_count',
    'Number of missing/zero features in namespace',
    ['asset', 'pipeline_id', 'namespace']
)

feature_namespace_sparsity = Gauge(
    'merid_feature_namespace_sparsity',
    'Sparsity ratio (missing / total) per namespace',
    ['asset', 'pipeline_id', 'namespace']
)

feature_agent_invocation_duration_seconds = Histogram(
    'merid_feature_agent_invocation_duration_seconds',
    'Time to invoke feature agent',
    ['asset', 'pipeline_id', 'agent_name', 'namespace'],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0]
)

feature_agent_invocation_errors = Counter(
    'merid_feature_agent_invocation_errors',
    'Number of feature agent invocation errors',
    ['asset', 'pipeline_id', 'agent_name', 'namespace', 'error_type']
)

feature_agent_invocation_success_rate = Gauge(
    'merid_feature_agent_invocation_success_rate',
    'Feature agent invocation success rate',
    ['asset', 'pipeline_id', 'agent_name', 'namespace']
)

# Risk Check Metrics
risk_check_total = Counter(
    'merid_risk_check_total',
    'Total number of risk checks performed',
    ['asset', 'pipeline_id', 'check_name']
)

risk_check_passed = Counter(
    'merid_risk_check_passed',
    'Number of risk checks passed',
    ['asset', 'pipeline_id', 'check_name']
)

risk_check_failed = Counter(
    'merid_risk_check_failed',
    'Number of risk checks failed',
    ['asset', 'pipeline_id', 'check_name']
)

risk_check_veto_rate = Gauge(
    'merid_risk_check_veto_rate',
    'Rate at which risk checks veto trades',
    ['asset', 'pipeline_id', 'check_name']
)

risk_adjustment_amount = Histogram(
    'merid_risk_adjustment_amount',
    'Amount of size adjustment by risk checks (pct)',
    ['asset', 'pipeline_id', 'check_name'],
    buckets=[0.0, 0.005, 0.01, 0.015, 0.02, 0.03, 0.04, 0.05]
)

# Execution Metrics
execution_orders_total = Counter(
    'merid_execution_orders_total',
    'Total number of orders executed',
    ['asset', 'pipeline_id']
)

execution_orders_success = Counter(
    'merid_execution_orders_success',
    'Number of successful order executions',
    ['asset', 'pipeline_id']
)

execution_orders_failed = Counter(
    'merid_execution_orders_failed',
    'Number of failed order executions',
    ['asset', 'pipeline_id', 'error_type']
)

execution_success_rate = Gauge(
    'merid_execution_success_rate',
    'Order execution success rate',
    ['asset', 'pipeline_id']
)

execution_pnl = Gauge(
    'merid_execution_pnl',
    'Cumulative PnL from executed orders',
    ['asset', 'pipeline_id']
)

execution_sharpe_ratio = Gauge(
    'merid_execution_sharpe_ratio',
    'Sharpe ratio of executed orders',
    ['asset', 'pipeline_id']
)

execution_max_drawdown = Gauge(
    'merid_execution_max_drawdown',
    'Maximum drawdown from executed orders',
    ['asset', 'pipeline_id']
)

# Health Metrics
pipeline_last_decision_timestamp = Gauge(
    'merid_pipeline_last_decision_timestamp',
    'Unix timestamp of last decision',
    ['asset', 'pipeline_id']
)

pipeline_last_cycle_timestamp = Gauge(
    'merid_pipeline_last_cycle_timestamp',
    'Unix timestamp of last pipeline cycle',
    ['asset', 'pipeline_id']
)

pipeline_healthy = Gauge(
    'merid_pipeline_healthy',
    'Pipeline health status (1=healthy, 0=unhealthy)',
    ['asset', 'pipeline_id']
)

feature_agent_healthy = Gauge(
    'merid_feature_agent_healthy',
    'Feature agent health status (1=healthy, 0=unhealthy)',
    ['asset', 'pipeline_id', 'agent_name']
)


class PipelineMetricsExporter:
    """
    Exports pipeline observability metrics to Prometheus.
    
    Maps PipelineObservability and DecisionTrace fields to Prometheus metrics.
    """
    
    def __init__(self):
        self.pipeline_success_counts: Dict[str, Dict[str, int]] = {}
        self.agent_success_counts: Dict[str, Dict[str, int]] = {}
    
    def export_trace(self, trace: Any) -> None:
        """Export a DecisionTrace to Prometheus metrics."""
        asset = trace.asset
        pipeline_id = trace.pipeline_id
        
        # Update cycle counts
        self.pipeline_success_counts.setdefault(asset, {}).setdefault(pipeline_id, {})
        self.pipeline_success_counts[asset][pipeline_id]['cycles'] = \
            self.pipeline_success_counts[asset][pipeline_id].get('cycles', 0) + 1
        
        # Export timing metrics
        pipeline_feature_build_duration_seconds.labels(
            asset=asset, pipeline_id=pipeline_id
        ).observe(trace.feature_build_ms / 1000)
        
        pipeline_decision_duration_seconds.labels(
            asset=asset, pipeline_id=pipeline_id
        ).observe(trace.decision_ms / 1000)
        
        pipeline_risk_check_duration_seconds.labels(
            asset=asset, pipeline_id=pipeline_id
        ).observe(trace.risk_check_ms / 1000)
        
        pipeline_execution_duration_seconds.labels(
            asset=asset, pipeline_id=pipeline_id
        ).observe(trace.execution_ms / 1000)
        
        pipeline_total_duration_seconds.labels(
            asset=asset, pipeline_id=pipeline_id
        ).observe(trace.total_ms / 1000)
        
        # Export feature namespace metrics
        for namespace, summary in trace.feature_summaries.items():
            feature_namespace_feature_count.labels(
                asset=asset, pipeline_id=pipeline_id, namespace=namespace
            ).set(summary.feature_count)
            
            feature_namespace_mean_value.labels(
                asset=asset, pipeline_id=pipeline_id, namespace=namespace
            ).set(summary.mean_value)
            
            feature_namespace_std_value.labels(
                asset=asset, pipeline_id=pipeline_id, namespace=namespace
            ).set(summary.std_value)
            
            feature_namespace_missing_count.labels(
                asset=asset, pipeline_id=pipeline_id, namespace=namespace
            ).set(summary.missing_count)
            
            # Calculate sparsity
            total = summary.feature_count + summary.missing_count
            sparsity = summary.missing_count / total if total > 0 else 0
            feature_namespace_sparsity.labels(
                asset=asset, pipeline_id=pipeline_id, namespace=namespace
            ).set(sparsity)
        
        # Export decision metrics
        if trace.decision:
            pipeline_decisions_total.labels(
                asset=asset, pipeline_id=pipeline_id, decision_side=trace.decision.side
            ).inc()
            
            pipeline_decisions_confidence.labels(
                asset=asset, pipeline_id=pipeline_id
            ).observe(trace.decision.confidence)
            
            pipeline_decisions_edge_estimate.labels(
                asset=asset, pipeline_id=pipeline_id
            ).observe(trace.decision.edge_estimate)
            
            pipeline_decisions_size_pct.labels(
                asset=asset, pipeline_id=pipeline_id
            ).observe(trace.decision.size_pct)
            
            self.pipeline_success_counts[asset][pipeline_id]['decisions'] = \
                self.pipeline_success_counts[asset][pipeline_id].get('decisions', 0) + 1
        
        # Export risk check metrics
        for risk_check in trace.risk_checks:
            check_name = risk_check['check_name']
            risk_check_total.labels(
                asset=asset, pipeline_id=pipeline_id, check_name=check_name
            ).inc()
            
            if risk_check['passed']:
                risk_check_passed.labels(
                    asset=asset, pipeline_id=pipeline_id, check_name=check_name
                ).inc()
            else:
                risk_check_failed.labels(
                    asset=asset, pipeline_id=pipeline_id, check_name=check_name
                ).inc()
            
            if risk_check.get('adjusted_size_pct'):
                original_size = trace.decision.size_pct if trace.decision else 0
                adjustment = original_size - risk_check['adjusted_size_pct']
                risk_adjustment_amount.labels(
                    asset=asset, pipeline_id=pipeline_id, check_name=check_name
                ).observe(adjustment)
        
        # Export execution metrics
        if trace.execution_success:
            execution_orders_success.labels(
                asset=asset, pipeline_id=pipeline_id
            ).inc()
        else:
            execution_orders_failed.labels(
                asset=asset, pipeline_id=pipeline_id, error_type=trace.execution_error
            ).inc()
        
        # Update success rate
        cycles = self.pipeline_success_counts[asset][pipeline_id].get('cycles', 0)
        decisions = self.pipeline_success_counts[asset][pipeline_id].get('decisions', 0)
        if cycles > 0:
            success_rate = decisions / cycles
            pipeline_success_rate.labels(
                asset=asset, pipeline_id=pipeline_id
            ).set(success_rate)
        
        # Update timestamps
        pipeline_last_cycle_timestamp.labels(
            asset=asset, pipeline_id=pipeline_id
        ).set(trace.timestamp.timestamp())
        
        if trace.decision:
            pipeline_last_decision_timestamp.labels(
                asset=asset, pipeline_id=pipeline_id
            ).set(trace.timestamp.timestamp())
    
    def export_health_metrics(self, observability: Any) -> None:
        """Export health metrics from PipelineObservability."""
        health_summary = observability.get_health_summary()
        
        # Export feature sparsity health
        for namespace, sparsity_data in health_summary.get('feature_sparsity', {}).items():
            avg_sparsity = sparsity_data.get('avg_sparsity', 0)
            # This is already exported per-trace, but we can add aggregated health here
            pass
    
    def export_agent_metrics(
        self,
        asset: str,
        pipeline_id: str,
        agent_name: str,
        namespace: str,
        duration_ms: float,
        success: bool,
    ) -> None:
        """Export feature agent invocation metrics."""
        feature_agent_invocation_duration_seconds.labels(
            asset=asset, pipeline_id=pipeline_id, agent_name=agent_name, namespace=namespace
        ).observe(duration_ms / 1000)
        
        # Update success counts
        key = f"{asset}:{pipeline_id}:{agent_name}"
        self.agent_success_counts.setdefault(key, {})
        self.agent_success_counts[key]['total'] = self.agent_success_counts[key].get('total', 0) + 1
        self.agent_success_counts[key]['success'] = self.agent_success_counts[key].get('success', 0) + (1 if success else 0)
        
        # Update success rate
        total = self.agent_success_counts[key]['total']
        success_rate = self.agent_success_counts[key]['success'] / total if total > 0 else 0
        feature_agent_invocation_success_rate.labels(
            asset=asset, pipeline_id=pipeline_id, agent_name=agent_name, namespace=namespace
        ).set(success_rate)
        
        # Update health status
        feature_agent_healthy.labels(
            asset=asset, pipeline_id=pipeline_id, agent_name=agent_name
        ).set(1 if success_rate > 0.8 else 0)


# Grafana Dashboard JSON (example structure)
GRAFANA_DASHBOARD_TEMPLATE = {
    "dashboard": {
        "title": "MERID 15m Pipeline Health",
        "panels": [
            {
                "title": "Decision Rate by Asset",
                "targets": [
                    {
                        "expr": "rate(merid_pipeline_decisions_total[5m])",
                        "legendFormat": "{{asset}}"
                    }
                ]
            },
            {
                "title": "Pipeline Success Rate",
                "targets": [
                    {
                        "expr": "merid_pipeline_success_rate",
                        "legendFormat": "{{asset}} - {{pipeline_id}}"
                    }
                ]
            },
            {
                "title": "Decision Confidence Distribution",
                "targets": [
                    {
                        "expr": "histogram_quantile(0.95, merid_pipeline_decisions_confidence)",
                        "legendFormat": "{{asset}}"
                    }
                ]
            },
            {
                "title": "Feature Namespace Sparsity",
                "targets": [
                    {
                        "expr": "merid_feature_namespace_sparsity",
                        "legendFormat": "{{asset}} - {{namespace}}"
                    }
                ]
            },
            {
                "title": "Pipeline Latency Breakdown",
                "targets": [
                    {
                        "expr": "histogram_quantile(0.95, merid_pipeline_feature_build_duration_seconds)",
                        "legendFormat": "Feature Build - {{asset}}"
                    },
                    {
                        "expr": "histogram_quantile(0.95, merid_pipeline_decision_duration_seconds)",
                        "legendFormat": "Decision - {{asset}}"
                    },
                    {
                        "expr": "histogram_quantile(0.95, merid_pipeline_risk_check_duration_seconds)",
                        "legendFormat": "Risk Check - {{asset}}"
                    }
                ]
            },
            {
                "title": "Risk Check Veto Rate",
                "targets": [
                    {
                        "expr": "merid_risk_check_veto_rate",
                        "legendFormat": "{{asset}} - {{check_name}}"
                    }
                ]
            },
            {
                "title": "Execution Success Rate",
                "targets": [
                    {
                        "expr": "merid_execution_success_rate",
                        "legendFormat": "{{asset}}"
                    }
                ]
            },
            {
                "title": "Cumulative PnL",
                "targets": [
                    {
                        "expr": "merid_execution_pnl",
                        "legendFormat": "{{asset}}"
                    }
                ]
            }
        ]
    }
}
