"""
Pytest fixtures for 15m trade path tests.

All fixtures ensure tests run under MERID_RUNTIME_MODE=15m_live.
"""

import pytest
import os
import time
from unittest.mock import Mock, MagicMock
from dataclasses import dataclass
from typing import Optional


@pytest.fixture(autouse=True)
def set_15m_mode():
    """Ensure all tests run in 15m live mode."""
    original_mode = os.environ.get('MERID_RUNTIME_MODE')
    original_profile = os.environ.get('MERID_PROFILE')
    
    os.environ['MERID_RUNTIME_MODE'] = '15m_live'
    os.environ['MERID_PROFILE'] = 'kalshi_crypto_15m_v2'
    
    yield
    
    # Restore original values
    if original_mode:
        os.environ['MERID_RUNTIME_MODE'] = original_mode
    elif 'MERID_RUNTIME_MODE' in os.environ:
        del os.environ['MERID_RUNTIME_MODE']
    
    if original_profile:
        os.environ['MERID_PROFILE'] = original_profile
    elif 'MERID_PROFILE' in os.environ:
        del os.environ['MERID_PROFILE']


@dataclass
class Signal:
    """Trading signal generated by agent."""
    asset: str
    market_id: str
    direction: str  # YES or NO
    contracts: int
    price_cents: int
    edge_pct: float
    timestamp: float


@dataclass
class Candidate:
    """Trade candidate after gate validation."""
    signal: Signal
    gate_decision: dict
    timestamp: float
    
    @property
    def market_id(self):
        """Convenience property to access signal market_id."""
        return self.signal.market_id


@dataclass
class Order:
    """Order placed with Kalshi."""
    order_id: str
    market_id: str
    direction: str
    contracts: int
    price_cents: int
    status: str  # PENDING, OPEN, FILLED, EXPIRED, CANCELLED
    timestamp: float


@dataclass
class Fill:
    """Fill confirmation from Kalshi."""
    order_id: str
    market_id: str
    direction: str
    contracts: int
    price_cents: int
    timestamp: float


@dataclass
class Position:
    """Position after fill."""
    market_id: str
    direction: str
    contracts: int
    entry_price_cents: int
    current_price_cents: Optional[int]
    pnl_cents: float


@pytest.fixture
def mock_agent():
    """Mock agent for signal generation."""
    agent = Mock()
    agent.asset = "BTC"
    agent.market_id = "BTC-15m-2026-06-05"
    agent.enabled = True
    return agent


@pytest.fixture
def mock_market_state():
    """Mock market state with healthy book."""
    state = Mock()
    state.book_consistency = "GOOD"
    state.suspect_reason = None
    state.bids = [[64, 100], [63, 200]]  # [price_cents, quantity]
    state.asks = [[66, 100], [67, 200]]
    state.mid_cents = 65
    state.best_bid_cents = 64
    state.best_ask_cents = 66
    state.last_update_ts = time.time() - 1
    return state


@pytest.fixture
def mock_spot_service():
    """Mock spot service with fresh data."""
    spot = Mock()
    spot.last_update_age = 5.0
    spot._running = True
    spot._freshness_threshold_s = 30.0
    spot.get_price = Mock(return_value=65000.0)
    return spot


@pytest.fixture
def mock_risk_env():
    """Mock risk environment with capacity."""
    risk = Mock()
    risk.utilization = Mock(return_value=0.3)
    risk.has_capacity = Mock(return_value=True)
    risk.update_position = Mock()
    risk.get_position = Mock(return_value=None)
    return risk


@pytest.fixture
def mock_kalshi_client():
    """Mock Kalshi client for order placement."""
    client = Mock()
    client.place_order = Mock(return_value="order_123")
    client.get_order_status = Mock(return_value="OPEN")
    return client


@pytest.fixture
def mock_fills_ledger():
    """Mock fills ledger for fill tracking."""
    ledger = Mock()
    ledger.record_fill = Mock()
    ledger.get_fills = Mock(return_value=[])
    return ledger


@pytest.fixture
def mock_order_router():
    """Mock order router for order placement."""
    router = Mock()
    router.place_order = Mock(return_value="order_123")
    return router


@pytest.fixture
def gate_decision_pass():
    """Mock gate decision with all gates passing."""
    return {
        "spot_age": "PASS",
        "book_freshness": "PASS",
        "liquidity": "PASS",
        "data_quality": "PASS",
        "edge": "PASS",
        "risk": "PASS",
        "overall": "PASS",
        "reason": None,
    }


@pytest.fixture
def gate_decision_fail():
    """Mock gate decision with edge gate failing."""
    return {
        "spot_age": "PASS",
        "book_freshness": "PASS",
        "liquidity": "PASS",
        "data_quality": "PASS",
        "edge": "FAIL",
        "risk": "PASS",
        "overall": "REJECT",
        "reason": "edge_insufficient",
    }


@pytest.fixture
def generate_signal():
    """Helper function to generate a trading signal."""
    def _generate(asset="BTC", market_id="BTC-15m-2026-06-05", direction="YES", contracts=10, price_cents=65, edge_pct=2.0):
        return Signal(
            asset=asset,
            market_id=market_id,
            direction=direction,
            contracts=contracts,
            price_cents=price_cents,
            edge_pct=edge_pct,
            timestamp=time.time(),
        )
    return _generate


@pytest.fixture
def create_candidate():
    """Helper function to create a trade candidate."""
    def _create(signal, gate_decision):
        return Candidate(
            signal=signal,
            gate_decision=gate_decision,
            timestamp=time.time(),
        )
    return _create


@pytest.fixture
def place_order():
    """Helper function to place an order."""
    def _place(candidate, kalshi_client):
        order_id = kalshi_client.place_order(
            market_id=candidate.signal.market_id,
            direction=candidate.signal.direction,
            contracts=candidate.signal.contracts,
            price_cents=candidate.signal.price_cents,
        )
        return Order(
            order_id=order_id,
            market_id=candidate.signal.market_id,
            direction=candidate.signal.direction,
            contracts=candidate.signal.contracts,
            price_cents=candidate.signal.price_cents,
            status="OPEN",
            timestamp=time.time(),
        )
    return _place


@pytest.fixture
def confirm_fill():
    """Helper function to confirm a fill."""
    def _confirm(order, fills_ledger):
        fill = Fill(
            order_id=order.order_id,
            market_id=order.market_id,
            direction=order.direction,
            contracts=order.contracts,
            price_cents=order.price_cents,
            timestamp=time.time(),
        )
        fills_ledger.record_fill(fill)
        return fill
    return _confirm


@pytest.fixture
def calculate_pnl():
    """Helper function to calculate PnL."""
    def _calculate(fill, settlement_price_cents, risk_env):
        # Calculate PnL: (settlement - entry) * contracts * direction
        # For YES: (settlement - entry) * contracts
        # For NO: (entry - settlement) * contracts
        if fill.direction == "YES":
            pnl_cents = (settlement_price_cents - fill.price_cents) * fill.contracts
        else:
            pnl_cents = (fill.price_cents - settlement_price_cents) * fill.contracts
        
        # Update risk environment
        risk_env.update_position(
            market_id=fill.market_id,
            contracts=fill.contracts,
            pnl_cents=pnl_cents,
        )
        
        return Position(
            market_id=fill.market_id,
            direction=fill.direction,
            contracts=fill.contracts,
            entry_price_cents=fill.price_cents,
            current_price_cents=settlement_price_cents,
            pnl_cents=pnl_cents,
        )
    return _calculate
